/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 boy.glb -T 
Files: boy.glb [1.08MB] > /Users/hsuwinlatt/Desktop/Work/Fullstack Empire/Youtube/threed-dev-portfolio/public/models/boy-transformed.glb [495.53KB] (54%)
*/

import { useAnimations, useFBX, useGLTF } from "@react-three/drei";
import { useEffect, useRef, useMemo } from "react";
import { SkeletonUtils } from "three-stdlib";

export function ContactAvatar(props) {
  const group = useRef();

  const { scene } = useGLTF("/models/avatarnew.glb");
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);

  const { animations } = useFBX("/models/Breakdance2.fbx");
  animations[0].name = "Dance";
  const action = useAnimations(animations, group);

  useEffect(() => {
    action.actions["Dance"].play();
  }, [action]);

  return (
    <group {...props} ref={group} dispose={null}>
      <primitive object={clone} />
    </group>
  );
}

useGLTF.preload("/models/avatarnew.glb");
