/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 cyber_orb.glb --transform 
Files: cyber_orb.glb [702.94KB] > /Users/stasshokarev/Desktop/development/personal-portfolio/public/models/cyber_orb-transformed.glb [206.51KB] (71%)
Author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyber-orb-8a81aa847da74a5cb36bd8ba13f6ae5e
Title: Cyber Orb
*/

import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function CyberOrb(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/cyber_orb-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);

  React.useEffect(() => {
    if (actions && Object.keys(actions).length > 0) {
      // Play the first available animation
      const firstAction = Object.values(actions)[0];
      if (firstAction) {
        firstAction.play();
      }
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group name="Sphere001_0">
            <mesh
              name="Object_4"
              geometry={nodes.Object_4.geometry}
              material={materials.shell}
            />
          </group>
          <group name="Sphere002_1" scale={0.72}>
            <mesh
              name="Object_6"
              geometry={nodes.Object_6.geometry}
              material={materials.material}
            />
          </group>
          <group name="Sphere003_2" />
          <group name="Sphere004_3">
            <mesh
              name="Object_9"
              geometry={nodes.Object_9.geometry}
              material={materials.frame}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/cyber_orb-transformed.glb");
