/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 rubber-duck.glb --transform 
Files: rubber-duck.glb [1.53MB] > /Users/stasshokarev/Desktop/development/personal-portfolio/public/models/rubber-duck-transformed.glb [75.18KB] (95%)
Author: Mylom (https://sketchfab.com/Mylom)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rubber-duck-add42e075bfd43ba9fe51766dc6b1b1c
Title: rubber-duck
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function RubberDuck(props) {
  const { nodes, materials } = useGLTF("/models/rubber-duck-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.defaultMaterial.geometry}
        material={materials.material}
        position={[0, 173.286, -2.915]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.901, 1.086, 1.022]}
      />
    </group>
  );
}

useGLTF.preload("/models/rubber-duck-transformed.glb");
